import type { Config } from 'tailwindcss'

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'inverse-primary': '#6bd8cb',
        'on-error': '#ffffff',
        'tertiary-container': '#727577',
        'surface-dim': '#cfdaf2',
        'on-tertiary-fixed-variant': '#444749',
        'on-tertiary-fixed': '#191c1e',
        'surface-container-high': '#dee8ff',
        background: '#f9f9ff',
        'surface-container-low': '#f0f3ff',
        'on-primary-fixed': '#00201d',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container': '#e7eeff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#00174b',
        'primary-fixed-dim': '#6bd8cb',
        'surface-container-highest': '#d8e3fb',
        'surface-tint': '#006a61',
        'on-primary-container': '#f4fffc',
        'on-background': '#111c2d',
        'inverse-surface': '#263143',
        'primary-fixed': '#89f5e7',
        tertiary: '#595c5e',
        'on-tertiary-container': '#fbfdff',
        'on-primary-fixed-variant': '#005049',
        'on-error-container': '#93000a',
        outline: '#6d7a77',
        'on-secondary-container': '#fefcff',
        primary: '#00685f',
        'outline-variant': '#bcc9c6',
        'on-secondary-fixed-variant': '#003ea8',
        'primary-container': '#008378',
        secondary: '#0051d5',
        'surface-variant': '#d8e3fb',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-primary': '#ffffff',
        'secondary-container': '#316bf3',
        'inverse-on-surface': '#ecf1ff',
        'on-surface-variant': '#3d4947',
        'secondary-fixed-dim': '#b4c5ff',
        'tertiary-fixed': '#e0e3e5',
        'on-surface': '#111c2d',
        surface: '#f9f9ff',
        'secondary-fixed': '#dbe1ff',
        'surface-bright': '#f9f9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '2rem',
        'margin-desktop': '40px',
        sm: '0.5rem',
        md: '1rem',
        gutter: '24px',
        'margin-mobile': '16px',
        base: '4px',
        lg: '1.5rem',
        xs: '0.25rem',
      },
      fontFamily: {
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'display-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  darkMode: 'class',
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
} satisfies Config
